//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LiveAppsOverlay.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LiveAppsOverlay.Localization.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apps.
        /// </summary>
        internal static string rsCapApps {
            get {
                return ResourceManager.GetString("rsCapApps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string rsCapCancel {
            get {
                return ResourceManager.GetString("rsCapCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for Updates.
        /// </summary>
        internal static string rsCapCheckForUpdates {
            get {
                return ResourceManager.GetString("rsCapCheckForUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Log.
        /// </summary>
        internal static string rsCapClearLog {
            get {
                return ResourceManager.GetString("rsCapClearLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display name.
        /// </summary>
        internal static string rsCapDisplayName {
            get {
                return ResourceManager.GetString("rsCapDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        internal static string rsCapDone {
            get {
                return ResourceManager.GetString("rsCapDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drag Mode.
        /// </summary>
        internal static string rsCapDragMode {
            get {
                return ResourceManager.GetString("rsCapDragMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Mode.
        /// </summary>
        internal static string rsCapEditMode {
            get {
                return ResourceManager.GetString("rsCapEditMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorites.
        /// </summary>
        internal static string rsCapFavorites {
            get {
                return ResourceManager.GetString("rsCapFavorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key.
        /// </summary>
        internal static string rsCapKey {
            get {
                return ResourceManager.GetString("rsCapKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logging.
        /// </summary>
        internal static string rsCapLogging {
            get {
                return ResourceManager.GetString("rsCapLogging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Hotkeys.
        /// </summary>
        internal static string rsCapManageHotkeys {
            get {
                return ResourceManager.GetString("rsCapManageHotkeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifier.
        /// </summary>
        internal static string rsCapModifier {
            get {
                return ResourceManager.GetString("rsCapModifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string rsCapName {
            get {
                return ResourceManager.GetString("rsCapName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process.
        /// </summary>
        internal static string rsCapProcess {
            get {
                return ResourceManager.GetString("rsCapProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Region Mode.
        /// </summary>
        internal static string rsCapRegionMode {
            get {
                return ResourceManager.GetString("rsCapRegionMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string rsCapSettings {
            get {
                return ResourceManager.GetString("rsCapSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle Edit Mode.
        /// </summary>
        internal static string rsCapToggleEditMode {
            get {
                return ResourceManager.GetString("rsCapToggleEditMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add process..
        /// </summary>
        internal static string rsTooltipAddProcess {
            get {
                return ResourceManager.GetString("rsTooltipAddProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for updates..
        /// </summary>
        internal static string rsTooltipCheckForUpdates {
            get {
                return ResourceManager.GetString("rsTooltipCheckForUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Config..
        /// </summary>
        internal static string rsTooltipConfig {
            get {
                return ResourceManager.GetString("rsTooltipConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit mode..
        /// </summary>
        internal static string rsTooltipEditMode {
            get {
                return ResourceManager.GetString("rsTooltipEditMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter name..
        /// </summary>
        internal static string rsTooltipEnterName {
            get {
                return ResourceManager.GetString("rsTooltipEnterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable/disable and change your hotkeys..
        /// </summary>
        internal static string rsTooltipManageHotkeys {
            get {
                return ResourceManager.GetString("rsTooltipManageHotkeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh handle..
        /// </summary>
        internal static string rsTooltipRefreshHandle {
            get {
                return ResourceManager.GetString("rsTooltipRefreshHandle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh process list..
        /// </summary>
        internal static string rsTooltipRefreshProcessList {
            get {
                return ResourceManager.GetString("rsTooltipRefreshProcessList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle drag mode..
        /// </summary>
        internal static string rsTooltipToggleDragMode {
            get {
                return ResourceManager.GetString("rsTooltipToggleDragMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle edit mode..
        /// </summary>
        internal static string rsTooltipToggleEditMode {
            get {
                return ResourceManager.GetString("rsTooltipToggleEditMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle edit mode hotkey on/off..
        /// </summary>
        internal static string rsTooltipToggleEditModeHotkey {
            get {
                return ResourceManager.GetString("rsTooltipToggleEditModeHotkey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle on/off..
        /// </summary>
        internal static string rsTooltipToggleOnOff {
            get {
                return ResourceManager.GetString("rsTooltipToggleOnOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle region mode..
        /// </summary>
        internal static string rsTooltipToggleRegionMode {
            get {
                return ResourceManager.GetString("rsTooltipToggleRegionMode", resourceCulture);
            }
        }
    }
}
